### ISSUE TITLE
Genie dashboard to visualize the model

### ISSUE THREAD

**Issue by PGimenez** [RobertGregg/CellularPotts.jl#52]
Hello! This is not really an issue, I just wanted to let you know that I've built a dashboard to visualize the Potts model with Genie. For now it's a simple demo that shows cell movement and a simple division. I've also recreated the visualization with PlotlyJS instead of Makie.  I'll add the app to the demo gallery at [learn.genieframework.com](learn.genieframework.com/app-gallery)

Here's the repo: https://github.com/BuiltWithGenie/CellPotts

![preview](https://github.com/RobertGregg/CellularPotts.jl/assets/5058397/b74b0dc3-3de3-436d-a16d-9ed4b5b89792)

Regards!

**Comment by RobertGregg** [comment]
Oh this is amazing! I've considered making an interactive visualization with Makie but never got around to it. Is it possible to integrate this into the documentation website? I also saw you were having some trouble with performance when adding the cell borders. Would removing the `sleep(0.1)` help or this that needed for PlotlyJS? Thank you again for setting this up!

**Comment by PGimenez** [comment]
Glad you liked it! We haven't hosted it anywhere, if we do I'll let you know so you can add it to the docs. It can be embedded with an iframe like we do in our docs here: https://learn.genieframework.com/docs/reference/reactive-ui/component-gallery
If you'd like to, you could link to the dashboard from this repo's readme

The issue I had was that I was drawing the plot in two steps: first the borders and then the fill. This caused the fill and border updates to the plot to not be in sync, and sometimes you'd see "ghost borders". Adding the 0.1 sleep fixed that. But still, I removed the borders as the full plot is transferred to the browser at each iteration (I'm using PlotlyJS) and this was slowing down the app.

It'd be great if we could integrate Makie plots in Genie apps, but [as of now it is not possible](https://github.com/MakieOrg/Makie.jl/issues/1813#issuecomment-2034374834).

**Comment by RobertGregg** [comment]
Awesome! Once the academic semester dies down I plan on updating this project. I'll definitely have to add a link to the readme and a section to the docs for the iframe example. 

I took a similar 2-step approach to plot the [borders](https://github.com/RobertGregg/CellularPotts.jl/blob/master/src/Visualization.jl#L49-L87)(they are deceptively difficult to get right because of off-by-one errors). I'm not super familiar with PlotlyJS, but maybe plotting all possible line segments first and changing the color alpha would be faster? I'll play around with it to find out. I too would to love to switch to Makie eventually because its becoming the de-facto plotting package in Julia. Hopefully WGLMakie eventually becomes compatible with Genie.
